name: Link Check
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          failIfEmpty: false
          args: --offline --verbose --no-progress --accept 200,429 '**/*.md' '**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
